help:
	@echo "up-dev"
	@echo "down-dev"
	@echo "up-prod"
	@echo "down-prod"


up-prod:
	@docker compose --profile prod up -d

down-prod:
	@docker compose --profile prod down

up-dev:
	@docker compose --profile dev up -d

down-dev:
	@docker compose --profile dev down
