// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Lightweight liveness probe",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Service health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rooms/quick-match": {
            "get": {
                "description": "Finds the best available room for the authenticated user and immediately joins it.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Matchmaking"
                ],
                "summary": "Quick match",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Game id",
                        "name": "game_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Minimum registration price",
                        "name": "min_registration_price",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum registration price",
                        "name": "max_registration_price",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Minimum room capacity",
                        "name": "min_capacity",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum room capacity",
                        "name": "max_capacity",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by boost availability",
                        "name": "is_boost",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Minimum boost power",
                        "name": "min_boost_power",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presenters.QuickMatchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/presenters.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/presenters.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/presenters.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/presenters.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/rooms/recommendations": {
            "get": {
                "description": "Returns recommended open rooms for the authenticated user based on filters and play history.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Matchmaking"
                ],
                "summary": "Recommend rooms",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Game id",
                        "name": "game_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Minimum registration price",
                        "name": "min_registration_price",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum registration price",
                        "name": "max_registration_price",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Minimum room capacity",
                        "name": "min_capacity",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum room capacity",
                        "name": "max_capacity",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by boost availability",
                        "name": "is_boost",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Minimum boost power",
                        "name": "min_boost_power",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presenters.RecommendRoomsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/presenters.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/presenters.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/presenters.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "presenters.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "presenters.Pagination": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "presenters.QuickMatchResponse": {
            "type": "object",
            "properties": {
                "reused_existing_room": {
                    "type": "boolean"
                },
                "room": {
                    "$ref": "#/definitions/presenters.RoomRecommendationResponse"
                },
                "round_id": {
                    "type": "integer"
                },
                "round_participant_id": {
                    "type": "integer"
                },
                "seat_number": {
                    "type": "integer"
                }
            }
        },
        "presenters.RecommendRoomsResponse": {
            "type": "object",
            "properties": {
                "cached": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presenters.RoomRecommendationResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/presenters.Pagination"
                }
            }
        },
        "presenters.RoomRecommendationResponse": {
            "type": "object",
            "properties": {
                "boost_power": {
                    "type": "integer"
                },
                "capacity": {
                    "type": "integer"
                },
                "config_id": {
                    "type": "integer"
                },
                "current_players": {
                    "type": "integer"
                },
                "game_id": {
                    "type": "integer"
                },
                "game_name": {
                    "type": "string"
                },
                "instance_key": {
                    "type": "string"
                },
                "is_boost": {
                    "type": "boolean"
                },
                "min_users": {
                    "type": "integer"
                },
                "redis_host": {
                    "type": "string"
                },
                "registration_price": {
                    "type": "integer"
                },
                "room_id": {
                    "type": "integer"
                },
                "score": {
                    "type": "number"
                },
                "server_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "LudoBox API",
	Description:      "LudoBox Matchmaking",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
